//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sglabo.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sglabo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   戦闘終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BattleEnd {
            get {
                return ResourceManager.GetString("BattleEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戦闘 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BattleStart {
            get {
                return ResourceManager.GetString("BattleStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィールド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アイテムロット中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemLot {
            get {
                return ResourceManager.GetString("ItemLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マップ判別コードを生成してクリップボードにコピーしました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MapCodeGenerated {
            get {
                return ResourceManager.GetString("MapCodeGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AIが見つかりません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoAIFound {
            get {
                return ResourceManager.GetString("NoAIFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SGプロセスが見つかりません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoProcessesFound {
            get {
                return ResourceManager.GetString("NoProcessesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行動中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NowActing {
            get {
                return ResourceManager.GetString("NowActing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NowMoving {
            get {
                return ResourceManager.GetString("NowMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理を開始しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessStarted {
            get {
                return ResourceManager.GetString("ProcessStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理を中断しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessStopped {
            get {
                return ResourceManager.GetString("ProcessStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マップスキャン... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ScanningBattleMap {
            get {
                return ResourceManager.GetString("ScanningBattleMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行動フェイズ待機中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WaitingForActionPhase {
            get {
                return ResourceManager.GetString("WaitingForActionPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動フェイズ待機中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WaitingForMovingPhase {
            get {
                return ResourceManager.GetString("WaitingForMovingPhase", resourceCulture);
            }
        }
    }
}
