//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sglabo.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sglabo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   戦闘終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BattleEnd {
            get {
                return ResourceManager.GetString("BattleEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戦闘 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BattleStart {
            get {
                return ResourceManager.GetString("BattleStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィールド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アイテムロット中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemLot {
            get {
                return ResourceManager.GetString("ItemLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   8x3
        ///0	0	1	484	168	1
        ///0	1	1	544	193	1
        ///0	2	0	604	250	1
        ///1	0	1	439	199	1
        ///1	1	0	498	257	1
        ///1	2	0	557	283	1
        ///2	0	0	391	263	1
        ///2	1	0	451	290	1
        ///2	2	0	512	317	1
        ///3	0	0	341	297	0
        ///3	1	0	404	325	1
        ///3	2	0	466	353	0
        ///4	0	0	295	332	1
        ///4	1	0	355	360	1
        ///4	2	0	415	387	1
        ///5	0	0	244	368	1
        ///5	1	0	304	395	1
        ///5	2	0	364	422	1
        ///6	0	0	191	404	1
        ///6	1	0	251	431	1
        ///6	2	0	311	458	1
        ///7	0	0	136	442	1
        ///7	1	0	196	470	1
        ///7	2	0	256	497	1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MAP60603230 {
            get {
                return ResourceManager.GetString("MAP60603230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マップ判別コードを生成してクリップボードにコピーしました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MapCodeGenerated {
            get {
                return ResourceManager.GetString("MapCodeGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AIが見つかりません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoAIFound {
            get {
                return ResourceManager.GetString("NoAIFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SGプロセスが見つかりません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoProcessesFound {
            get {
                return ResourceManager.GetString("NoProcessesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行動中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NowActing {
            get {
                return ResourceManager.GetString("NowActing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NowMoving {
            get {
                return ResourceManager.GetString("NowMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理を開始しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessStarted {
            get {
                return ResourceManager.GetString("ProcessStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理を中断しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessStopped {
            get {
                return ResourceManager.GetString("ProcessStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マップスキャン... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ScanningBattleMap {
            get {
                return ResourceManager.GetString("ScanningBattleMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行動フェイズ待機中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WaitingForActionPhase {
            get {
                return ResourceManager.GetString("WaitingForActionPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動フェイズ待機中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WaitingForMovingPhase {
            get {
                return ResourceManager.GetString("WaitingForMovingPhase", resourceCulture);
            }
        }
    }
}
